<a href="https://colab.research.google.com/github/laxmijin11-cyber/MACHINE-LEARNING/blob/main/knn%20/1_knn_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
# KNN Classifier Implementation
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
# Displays matplotlib plots DIRECTLY inside your Jupyter Notebook (not in a separate pop-up window).

In [43]:
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000, #1000 observations
                        n_features=3, #3 total feature
                        n_redundant=1,
                        n_classes=2,  #binary target or label
                        random_state=999)

Feature 1: Informative (real info)

Feature 2: Informative (real info)

Feature 3: Redundant (combination of feature 1 & 2)

## Why Add Redundant Features in KNN?

---

### The Problem: KNN is Distance-Based

KNN works by calculating **distance** between points (Euclidean distance).

---

### What Redundant Features Do:

| Feature Type | Effect on Distance |
|--------------|-------------------|
| **Informative** | Helps separate classes  |
| **Redundant** | Amplifies existing features  |

---

### Example:

Without redundant (2 features):
```
Point A: (age=25, income=50k)
Point B: (age=30, income=60k)
Distance = small (good)
```

With redundant (3rd feature = age + income):
```
Point A: (25, 50k, 25+50k=50025)
Point B: (30, 60k, 30+60k=60030)
Distance = now MUCH larger! ❌
```

**The redundant feature DOMINATES the distance calculation.**

---




### What Happens to KNN:

| Without scaling | With scaling |
|----------------|--------------|
| Redundant feature dominates | All features contribute equally |
| Poor accuracy | Better accuracy |
| Distance skewed | Distance balanced |

---

### Lesson:

**Redundant features are BAD for KNN** unless you:
1. **Scale** your data (StandardScaler, MinMaxScaler)
2. **Remove** redundant features (feature selection)

In [44]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [45]:
x

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [46]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,

In [47]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,algorithm='auto')

In [48]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [49]:
ypred=classifier.predict(x_test)

In [50]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test,ypred))
print(confusion_matrix(y_test,ypred))
print(classification_report(y_test,ypred))

0.906060606060606
[[158  11]
 [ 20 141]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       169
           1       0.93      0.88      0.90       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



In [51]:
# HyperParameter Tuning
from sklearn.model_selection import GridSearchCV
param_grid={'n_neighbors':[1,2,3,4,5,6,7,8,9,10],
            'p':[1,2],
            'algorithm':['brute','auto','ball_tree','kd_tree'],
            'weights':['uniform','distance']}

In [52]:
grid=GridSearchCV(classifier,param_grid,refit=True,verbose=2,cv=5)

After cross-validation, train the final model on ALL data using the best hyperparameters found:refit=True

In [53]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 160 candidates, totalling 800 fits
[CV] END algorithm=brute, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_ne

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['brute', 'auto', 'ball_tree', 'kd_tree'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             verbose=2)

In [54]:
grid.best_params_

{'algorithm': 'brute', 'n_neighbors': 9, 'p': 2, 'weights': 'uniform'}

In [55]:
ypred1=grid.predict(x_test)

ypred1=grid.predict(x_test)::

when i say this it runs with best parameters of gridsearchcv....

In [56]:
print(accuracy_score(y_test,ypred1))

0.9121212121212121



---

| Order | Meaning |
|-------|---------|
| `classification_report(y_test, y_pred)` | ✅ **CORRECT** (True, then Predicted) |
| `classification_report(y_pred, y_test)` | ❌ **WRONG** (Swapped) |

---

### Why Order Matters:

The function expects: `(true_values, predicted_values)`

| First argument | Second argument |
|----------------|-----------------|
| Actual truth | Your prediction |



---
This comes to the end of KNN Classifier!!